require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRailsVersion: 5.2
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*_spec.rb'

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
